from typing import Generator, Iterable, List


class proper(object):
    def __init__(self, arr:List) -> None: ...
    def comb(self) -> Generator: ...
    def perm(self) -> List: ...
    def __create_perm(self, arr:List, next:int) -> None: ...

class cheater(object):
    def __init__(self, arr:List) -> None: ...
    def comb(self) -> Generator: ...
    def perm(self) -> Generator: ...
    